version: '3'

services:
  registry:
    container_name: registry
    hostname: registry
    image: registry:2
    ports:
    - 5000:5000

  testcase:
    container_name: testcase
    hostname: testcase
    image: localhost:5000/testcase:0.0.1
    ports:
    - 80:80
