apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2019-09-01T13:26:02Z
  labels:
    app: kibana
  name: kibana
  namespace: custom
  resourceVersion: "133535"
  selfLink: /apis/route.openshift.io/v1/namespaces/custom/routes/kibana
  uid: 0b0c0971-ccbc-11e9-9a82-005056a37de3
spec:
  host: kibana-custom.router.default.svc.cluster.local
  port:
    targetPort: 5601-tcp
  to:
    kind: Service
    name: kibana
    weight: 100
  wildcardPolicy: None
status:
  ingress: null
