apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.elastic.co/kibana/kibana:6.3.2
      from:
        kind: DockerImage
        name: docker.elastic.co/kibana/kibana:6.3.2
      generation: null
      importPolicy: {}
      name: 6.3.2
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    replicas: 1
    selector:
      app: kibana
      deploymentconfig: kibana
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: kibana
          deploymentconfig: kibana
      spec:
        containers:
        - env:
          - name: ELASTICSEARCH_URL
            value: http://es:9200
          image: docker.elastic.co/kibana/kibana:6.3.2
          name: kibana
          ports:
          - containerPort: 5601
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kibana
        from:
          kind: ImageStreamTag
          name: kibana:6.3.2
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    ports:
    - name: 5601-tcp
      port: 5601
      protocol: TCP
      targetPort: 5601
    selector:
      app: kibana
      deploymentconfig: kibana
  status:
    loadBalancer: {}
kind: List
metadata: {}
