apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: odoo
    name: odoo
  spec:
    replicas: 1
    selector:
      app: odoo
      deploymentconfig: odoo
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: odoo
          deploymentconfig: odoo
      spec:
        containers:
        - env:
          - name: HOST
            value: pg
          - name: PASSWORD
            value: odoo
          - name: USER
            value: odoo
          image: docker-registry.default.svc:5000/custom/odoo:latest
          name: odoo
          ports:
          - containerPort: 8071
            protocol: TCP
          - containerPort: 8069
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/odoo
            name: odoo-volume-1
          - mountPath: /mnt/extra-addons
            name: odoo-volume-2
        volumes:
        - emptyDir: {}
          name: odoo-volume-1
        - emptyDir: {}
          name: odoo-volume-2
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - odoo
        from:
          kind: ImageStreamTag
          name: odoo:latest
          namespace: custom
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: odoo
    name: odoo
  spec:
    ports:
    - name: 8069-tcp
      port: 8069
      protocol: TCP
      targetPort: 8069
    - name: 8071-tcp
      port: 8071
      protocol: TCP
      targetPort: 8071
    selector:
      app: odoo
      deploymentconfig: odoo
  status:
    loadBalancer: {}
kind: List
metadata: {}
