apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pg
    name: pg
  spec:
    replicas: 1
    selector:
      app: pg
      deploymentconfig: pg
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: pg
          deploymentconfig: pg
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: odoo
          - name: POSTGRESQL_PASSWORD
            value: odoo
          - name: POSTGRESQL_USER
            value: odoo
          image: centos/postgresql-94-centos7
          name: pg
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: pg-volume-1
        volumes:
        - emptyDir: {}
          name: pg-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pg
        from:
          kind: ImageStreamTag
          name: pg:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pg
    name: pg
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: pg
      deploymentconfig: pg
  status:
    loadBalancer: {}
kind: List
metadata: {}
